version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes: 
      - ${MYSQL_PATH_DB}:/var/lib/mysql
    restart: always

  web:
    build: .
    container_name: web
    image: web:1.0.0
    volumes:
      - ${HOST_APP_PATH}:/var/www/html
    ports:
      - ${APACHE_HOST_PORT}:80
    depends_on:
      - mysql
    environment:
      WEB_DOCUMENT_ROOT: "/var/www/html"

  composer:
    image: composer:2.0
    container_name: composer
    command: ["composer", "install"]
    volumes:
      - ${HOST_APP_PATH}:/app
